spring.application.name=VolunteerHubApi

server.port=${SERVER_PORT:8082}

spring.mongodb.host=${MONGODB_HOST:localhost}
spring.mongodb.port=${MONGODB_PORT:27017}
spring.mongodb.database=${MONGODB_DATABASE:volunteerhub}
spring.mongodb.authentication-database=${MONGODB_AUTHENTICATION_DATABASE:volunteerhub}
spring.mongodb.username=${MONGODB_USERNAME}
spring.mongodb.password=${MONGODB_PASSWORD}

spring.data.mongodb.auto-index-creation=true

spring.jackson.serialization.indent-output=true
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always
spring.web.error.include-stacktrace=always

logging.level.root=INFO
logging.level.com.volunteerhub.backend=DEBUG

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-minutes=${JWT_EXPIRATION_MINUTES:60}

server.tomcat.basedir=C:/tomcat-temp